/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLicensesRouteImport } from './routes/admin-licenses'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerVaultRouteImport } from './routes/owner-vault'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as Char1575Char1604Char1607Char1608Char1610Char1577RouteImport } from './routes/الهوية'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCheckoutConfigRouteImport } from './routes/api/checkout/config'
import { Route as ApiLicenseActivateRouteImport } from './routes/api/license/activate'
import { Route as ApiLicenseDeactivateRouteImport } from './routes/api/license/deactivate'
import { Route as ApiLicenseValidateRouteImport } from './routes/api/license/validate'
import { Route as ApiWebhooksLemonsqueezyRouteImport } from './routes/api/webhooks/lemonsqueezy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/admin-licenses',
  path: '/admin-licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerVaultRoute = OwnerVaultRouteImport.update({
  id: '/owner-vault',
  path: '/owner-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const Char1575Char1604Char1607Char1608Char1610Char1577Route =
  Char1575Char1604Char1607Char1608Char1610Char1577RouteImport.update({
    id: '/الهوية',
    path: '/الهوية',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutConfigRoute = ApiCheckoutConfigRouteImport.update({
  id: '/api/checkout/config',
  path: '/api/checkout/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseActivateRoute = ApiLicenseActivateRouteImport.update({
  id: '/api/license/activate',
  path: '/api/license/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseDeactivateRoute = ApiLicenseDeactivateRouteImport.update({
  id: '/api/license/deactivate',
  path: '/api/license/deactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseValidateRoute = ApiLicenseValidateRouteImport.update({
  id: '/api/license/validate',
  path: '/api/license/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksLemonsqueezyRoute = ApiWebhooksLemonsqueezyRouteImport.update({
  id: '/api/webhooks/lemonsqueezy',
  path: '/api/webhooks/lemonsqueezy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-licenses': typeof AdminLicensesRoute
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/editor': typeof EditorRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/owner-vault': typeof OwnerVaultRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/templates': typeof TemplatesRoute
  '/الهوية': typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/config': typeof ApiCheckoutConfigRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/validate': typeof ApiLicenseValidateRoute
  '/api/webhooks/lemonsqueezy': typeof ApiWebhooksLemonsqueezyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-licenses': typeof AdminLicensesRoute
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/editor': typeof EditorRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/owner-vault': typeof OwnerVaultRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/templates': typeof TemplatesRoute
  '/الهوية': typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/config': typeof ApiCheckoutConfigRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/validate': typeof ApiLicenseValidateRoute
  '/api/webhooks/lemonsqueezy': typeof ApiWebhooksLemonsqueezyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-licenses': typeof AdminLicensesRoute
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/editor': typeof EditorRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/owner-vault': typeof OwnerVaultRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/templates': typeof TemplatesRoute
  '/الهوية': typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/config': typeof ApiCheckoutConfigRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/validate': typeof ApiLicenseValidateRoute
  '/api/webhooks/lemonsqueezy': typeof ApiWebhooksLemonsqueezyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-licenses'
    | '/brand-kit'
    | '/contact'
    | '/demo'
    | '/editor'
    | '/license'
    | '/login'
    | '/owner-vault'
    | '/projects'
    | '/purchase'
    | '/templates'
    | '/الهوية'
    | '/api/auth/$'
    | '/api/checkout/config'
    | '/api/license/activate'
    | '/api/license/deactivate'
    | '/api/license/validate'
    | '/api/webhooks/lemonsqueezy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-licenses'
    | '/brand-kit'
    | '/contact'
    | '/demo'
    | '/editor'
    | '/license'
    | '/login'
    | '/owner-vault'
    | '/projects'
    | '/purchase'
    | '/templates'
    | '/الهوية'
    | '/api/auth/$'
    | '/api/checkout/config'
    | '/api/license/activate'
    | '/api/license/deactivate'
    | '/api/license/validate'
    | '/api/webhooks/lemonsqueezy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-licenses'
    | '/brand-kit'
    | '/contact'
    | '/demo'
    | '/editor'
    | '/license'
    | '/login'
    | '/owner-vault'
    | '/projects'
    | '/purchase'
    | '/templates'
    | '/الهوية'
    | '/api/auth/$'
    | '/api/checkout/config'
    | '/api/license/activate'
    | '/api/license/deactivate'
    | '/api/license/validate'
    | '/api/webhooks/lemonsqueezy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  BrandKitRoute: typeof BrandKitRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  EditorRoute: typeof EditorRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  OwnerVaultRoute: typeof OwnerVaultRoute
  ProjectsRoute: typeof ProjectsRoute
  PurchaseRoute: typeof PurchaseRoute
  TemplatesRoute: typeof TemplatesRoute
  Char1575Char1604Char1607Char1608Char1610Char1577Route: typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutConfigRoute: typeof ApiCheckoutConfigRoute
  ApiLicenseActivateRoute: typeof ApiLicenseActivateRoute
  ApiLicenseDeactivateRoute: typeof ApiLicenseDeactivateRoute
  ApiLicenseValidateRoute: typeof ApiLicenseValidateRoute
  ApiWebhooksLemonsqueezyRoute: typeof ApiWebhooksLemonsqueezyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-licenses': {
      id: '/admin-licenses'
      path: '/admin-licenses'
      fullPath: '/admin-licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-vault': {
      id: '/owner-vault'
      path: '/owner-vault'
      fullPath: '/owner-vault'
      preLoaderRoute: typeof OwnerVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/الهوية': {
      id: '/الهوية'
      path: '/الهوية'
      fullPath: '/الهوية'
      preLoaderRoute: typeof Char1575Char1604Char1607Char1608Char1610Char1577RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/config': {
      id: '/api/checkout/config'
      path: '/api/checkout/config'
      fullPath: '/api/checkout/config'
      preLoaderRoute: typeof ApiCheckoutConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/activate': {
      id: '/api/license/activate'
      path: '/api/license/activate'
      fullPath: '/api/license/activate'
      preLoaderRoute: typeof ApiLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/deactivate': {
      id: '/api/license/deactivate'
      path: '/api/license/deactivate'
      fullPath: '/api/license/deactivate'
      preLoaderRoute: typeof ApiLicenseDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/validate': {
      id: '/api/license/validate'
      path: '/api/license/validate'
      fullPath: '/api/license/validate'
      preLoaderRoute: typeof ApiLicenseValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/lemonsqueezy': {
      id: '/api/webhooks/lemonsqueezy'
      path: '/api/webhooks/lemonsqueezy'
      fullPath: '/api/webhooks/lemonsqueezy'
      preLoaderRoute: typeof ApiWebhooksLemonsqueezyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  BrandKitRoute: BrandKitRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  EditorRoute: EditorRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  OwnerVaultRoute: OwnerVaultRoute,
  ProjectsRoute: ProjectsRoute,
  PurchaseRoute: PurchaseRoute,
  TemplatesRoute: TemplatesRoute,
  Char1575Char1604Char1607Char1608Char1610Char1577Route:
    Char1575Char1604Char1607Char1608Char1610Char1577Route,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutConfigRoute: ApiCheckoutConfigRoute,
  ApiLicenseActivateRoute: ApiLicenseActivateRoute,
  ApiLicenseDeactivateRoute: ApiLicenseDeactivateRoute,
  ApiLicenseValidateRoute: ApiLicenseValidateRoute,
  ApiWebhooksLemonsqueezyRoute: ApiWebhooksLemonsqueezyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
