/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CustomDesignRouteImport } from './routes/custom-design'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpenRouteImport } from './routes/open'
import { Route as OwnerVaultRouteImport } from './routes/owner-vault'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as Char1575Char1604Char1607Char1608Char1610Char1577RouteImport } from './routes/الهوية'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAssetsRouteImport } from './routes/admin/assets'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBrandingRouteImport } from './routes/admin/branding'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStudioRouteImport } from './routes/admin/studio'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAppVersionRouteImport } from './routes/api/app-version'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as EditorProjectIdRouteImport } from './routes/editor/$projectId'
import { Route as PaymentCancelRouteImport } from './routes/payment/cancel'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as SCodeRouteImport } from './routes/s/$code'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as TCodeRouteImport } from './routes/t/$code'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as AdminLicensesIndexRouteImport } from './routes/admin/licenses/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLicenseActivateRouteImport } from './routes/api/license/activate'
import { Route as ApiLicenseDeactivateRouteImport } from './routes/api/license/deactivate'
import { Route as ApiLicenseValidateRouteImport } from './routes/api/license/validate'
import { Route as ApiTemplatesThumbnailRouteImport } from './routes/api/templates/thumbnail'
import { Route as ApiWebhooksGumroadRouteImport } from './routes/api/webhooks/gumroad'
import { Route as ApiWebhooksKeygenRouteImport } from './routes/api/webhooks/keygen'
import { Route as TemplatesTemplateIdPreviewRouteImport } from './routes/templates/$templateId.preview'
import { Route as TemplatesTemplateIdShareRouteImport } from './routes/templates/$templateId.share'
import { Route as TemplatesShareTokenRouteImport } from './routes/templates/share/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDesignRoute = CustomDesignRouteImport.update({
  id: '/custom-design',
  path: '/custom-design',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerVaultRoute = OwnerVaultRouteImport.update({
  id: '/owner-vault',
  path: '/owner-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const Char1575Char1604Char1607Char1608Char1610Char1577Route =
  Char1575Char1604Char1607Char1608Char1610Char1577RouteImport.update({
    id: '/الهوية',
    path: '/الهوية',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudioRoute = AdminStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAppVersionRoute = ApiAppVersionRouteImport.update({
  id: '/api/app-version',
  path: '/api/app-version',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplatesRoute,
} as any)
const AdminLicensesIndexRoute = AdminLicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseActivateRoute = ApiLicenseActivateRouteImport.update({
  id: '/api/license/activate',
  path: '/api/license/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseDeactivateRoute = ApiLicenseDeactivateRouteImport.update({
  id: '/api/license/deactivate',
  path: '/api/license/deactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseValidateRoute = ApiLicenseValidateRouteImport.update({
  id: '/api/license/validate',
  path: '/api/license/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesThumbnailRoute = ApiTemplatesThumbnailRouteImport.update({
  id: '/api/templates/thumbnail',
  path: '/api/templates/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGumroadRoute = ApiWebhooksGumroadRouteImport.update({
  id: '/api/webhooks/gumroad',
  path: '/api/webhooks/gumroad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksKeygenRoute = ApiWebhooksKeygenRouteImport.update({
  id: '/api/webhooks/keygen',
  path: '/api/webhooks/keygen',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdPreviewRoute =
  TemplatesTemplateIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => TemplatesTemplateIdRoute,
  } as any)
const TemplatesTemplateIdShareRoute =
  TemplatesTemplateIdShareRouteImport.update({
    id: '/share',
    path: '/share',
    getParentRoute: () => TemplatesTemplateIdRoute,
  } as any)
const TemplatesShareTokenRoute = TemplatesShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => TemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/custom-design': typeof CustomDesignRoute
  '/demo': typeof DemoRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/open': typeof OpenRoute
  '/owner-vault': typeof OwnerVaultRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/purchase': typeof PurchaseRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
  '/الهوية': typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/app-version': typeof ApiAppVersionRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/s/$code': typeof SCodeRoute
  '/share/$token': typeof ShareTokenRoute
  '/t/$code': typeof TCodeRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/validate': typeof ApiLicenseValidateRoute
  '/api/templates/thumbnail': typeof ApiTemplatesThumbnailRoute
  '/api/webhooks/gumroad': typeof ApiWebhooksGumroadRoute
  '/api/webhooks/keygen': typeof ApiWebhooksKeygenRoute
  '/templates/$templateId/preview': typeof TemplatesTemplateIdPreviewRoute
  '/templates/$templateId/share': typeof TemplatesTemplateIdShareRoute
  '/templates/share/$token': typeof TemplatesShareTokenRoute
  '/admin/licenses/': typeof AdminLicensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/custom-design': typeof CustomDesignRoute
  '/demo': typeof DemoRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/open': typeof OpenRoute
  '/owner-vault': typeof OwnerVaultRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/purchase': typeof PurchaseRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
  '/الهوية': typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/app-version': typeof ApiAppVersionRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/s/$code': typeof SCodeRoute
  '/share/$token': typeof ShareTokenRoute
  '/t/$code': typeof TCodeRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/editor': typeof EditorIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/validate': typeof ApiLicenseValidateRoute
  '/api/templates/thumbnail': typeof ApiTemplatesThumbnailRoute
  '/api/webhooks/gumroad': typeof ApiWebhooksGumroadRoute
  '/api/webhooks/keygen': typeof ApiWebhooksKeygenRoute
  '/templates/$templateId/preview': typeof TemplatesTemplateIdPreviewRoute
  '/templates/$templateId/share': typeof TemplatesTemplateIdShareRoute
  '/templates/share/$token': typeof TemplatesShareTokenRoute
  '/admin/licenses': typeof AdminLicensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/brand-kit': typeof BrandKitRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/custom-design': typeof CustomDesignRoute
  '/demo': typeof DemoRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/license': typeof LicenseRoute
  '/login': typeof LoginRoute
  '/open': typeof OpenRoute
  '/owner-vault': typeof OwnerVaultRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/purchase': typeof PurchaseRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
  '/الهوية': typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/app-version': typeof ApiAppVersionRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/s/$code': typeof SCodeRoute
  '/share/$token': typeof ShareTokenRoute
  '/t/$code': typeof TCodeRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/validate': typeof ApiLicenseValidateRoute
  '/api/templates/thumbnail': typeof ApiTemplatesThumbnailRoute
  '/api/webhooks/gumroad': typeof ApiWebhooksGumroadRoute
  '/api/webhooks/keygen': typeof ApiWebhooksKeygenRoute
  '/templates/$templateId/preview': typeof TemplatesTemplateIdPreviewRoute
  '/templates/$templateId/share': typeof TemplatesTemplateIdShareRoute
  '/templates/share/$token': typeof TemplatesShareTokenRoute
  '/admin/licenses/': typeof AdminLicensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/brand-kit'
    | '/contact'
    | '/create'
    | '/custom-design'
    | '/demo'
    | '/import'
    | '/library'
    | '/license'
    | '/login'
    | '/open'
    | '/owner-vault'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/purchase'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/workspace'
    | '/الهوية'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/branding'
    | '/admin/content'
    | '/admin/import'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/studio'
    | '/admin/templates'
    | '/admin/users'
    | '/api/app-version'
    | '/editor/$projectId'
    | '/payment/cancel'
    | '/payment/success'
    | '/projects/$projectId'
    | '/s/$code'
    | '/share/$token'
    | '/t/$code'
    | '/templates/$templateId'
    | '/admin/'
    | '/editor/'
    | '/templates/'
    | '/api/auth/$'
    | '/api/license/activate'
    | '/api/license/deactivate'
    | '/api/license/validate'
    | '/api/templates/thumbnail'
    | '/api/webhooks/gumroad'
    | '/api/webhooks/keygen'
    | '/templates/$templateId/preview'
    | '/templates/$templateId/share'
    | '/templates/share/$token'
    | '/admin/licenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/brand-kit'
    | '/contact'
    | '/create'
    | '/custom-design'
    | '/demo'
    | '/import'
    | '/library'
    | '/license'
    | '/login'
    | '/open'
    | '/owner-vault'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/purchase'
    | '/studio'
    | '/terms'
    | '/workspace'
    | '/الهوية'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/branding'
    | '/admin/content'
    | '/admin/import'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/studio'
    | '/admin/templates'
    | '/admin/users'
    | '/api/app-version'
    | '/editor/$projectId'
    | '/payment/cancel'
    | '/payment/success'
    | '/projects/$projectId'
    | '/s/$code'
    | '/share/$token'
    | '/t/$code'
    | '/templates/$templateId'
    | '/admin'
    | '/editor'
    | '/templates'
    | '/api/auth/$'
    | '/api/license/activate'
    | '/api/license/deactivate'
    | '/api/license/validate'
    | '/api/templates/thumbnail'
    | '/api/webhooks/gumroad'
    | '/api/webhooks/keygen'
    | '/templates/$templateId/preview'
    | '/templates/$templateId/share'
    | '/templates/share/$token'
    | '/admin/licenses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/brand-kit'
    | '/contact'
    | '/create'
    | '/custom-design'
    | '/demo'
    | '/import'
    | '/library'
    | '/license'
    | '/login'
    | '/open'
    | '/owner-vault'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/purchase'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/workspace'
    | '/الهوية'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/branding'
    | '/admin/content'
    | '/admin/import'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/studio'
    | '/admin/templates'
    | '/admin/users'
    | '/api/app-version'
    | '/editor/$projectId'
    | '/payment/cancel'
    | '/payment/success'
    | '/projects/$projectId'
    | '/s/$code'
    | '/share/$token'
    | '/t/$code'
    | '/templates/$templateId'
    | '/admin/'
    | '/editor/'
    | '/templates/'
    | '/api/auth/$'
    | '/api/license/activate'
    | '/api/license/deactivate'
    | '/api/license/validate'
    | '/api/templates/thumbnail'
    | '/api/webhooks/gumroad'
    | '/api/webhooks/keygen'
    | '/templates/$templateId/preview'
    | '/templates/$templateId/share'
    | '/templates/share/$token'
    | '/admin/licenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrandKitRoute: typeof BrandKitRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  CustomDesignRoute: typeof CustomDesignRoute
  DemoRoute: typeof DemoRoute
  ImportRoute: typeof ImportRoute
  LibraryRoute: typeof LibraryRoute
  LicenseRoute: typeof LicenseRoute
  LoginRoute: typeof LoginRoute
  OpenRoute: typeof OpenRoute
  OwnerVaultRoute: typeof OwnerVaultRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PurchaseRoute: typeof PurchaseRoute
  StudioRoute: typeof StudioRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TermsRoute: typeof TermsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  Char1575Char1604Char1607Char1608Char1610Char1577Route: typeof Char1575Char1604Char1607Char1608Char1610Char1577Route
  ApiAppVersionRoute: typeof ApiAppVersionRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  SCodeRoute: typeof SCodeRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TCodeRoute: typeof TCodeRoute
  EditorIndexRoute: typeof EditorIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLicenseActivateRoute: typeof ApiLicenseActivateRoute
  ApiLicenseDeactivateRoute: typeof ApiLicenseDeactivateRoute
  ApiLicenseValidateRoute: typeof ApiLicenseValidateRoute
  ApiTemplatesThumbnailRoute: typeof ApiTemplatesThumbnailRoute
  ApiWebhooksGumroadRoute: typeof ApiWebhooksGumroadRoute
  ApiWebhooksKeygenRoute: typeof ApiWebhooksKeygenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-design': {
      id: '/custom-design'
      path: '/custom-design'
      fullPath: '/custom-design'
      preLoaderRoute: typeof CustomDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-vault': {
      id: '/owner-vault'
      path: '/owner-vault'
      fullPath: '/owner-vault'
      preLoaderRoute: typeof OwnerVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/الهوية': {
      id: '/الهوية'
      path: '/الهوية'
      fullPath: '/الهوية'
      preLoaderRoute: typeof Char1575Char1604Char1607Char1608Char1610Char1577RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studio': {
      id: '/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AdminStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/app-version': {
      id: '/api/app-version'
      path: '/api/app-version'
      fullPath: '/api/app-version'
      preLoaderRoute: typeof ApiAppVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/admin/licenses/': {
      id: '/admin/licenses/'
      path: '/licenses'
      fullPath: '/admin/licenses/'
      preLoaderRoute: typeof AdminLicensesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/activate': {
      id: '/api/license/activate'
      path: '/api/license/activate'
      fullPath: '/api/license/activate'
      preLoaderRoute: typeof ApiLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/deactivate': {
      id: '/api/license/deactivate'
      path: '/api/license/deactivate'
      fullPath: '/api/license/deactivate'
      preLoaderRoute: typeof ApiLicenseDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/validate': {
      id: '/api/license/validate'
      path: '/api/license/validate'
      fullPath: '/api/license/validate'
      preLoaderRoute: typeof ApiLicenseValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/thumbnail': {
      id: '/api/templates/thumbnail'
      path: '/api/templates/thumbnail'
      fullPath: '/api/templates/thumbnail'
      preLoaderRoute: typeof ApiTemplatesThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/gumroad': {
      id: '/api/webhooks/gumroad'
      path: '/api/webhooks/gumroad'
      fullPath: '/api/webhooks/gumroad'
      preLoaderRoute: typeof ApiWebhooksGumroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/keygen': {
      id: '/api/webhooks/keygen'
      path: '/api/webhooks/keygen'
      fullPath: '/api/webhooks/keygen'
      preLoaderRoute: typeof ApiWebhooksKeygenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId/preview': {
      id: '/templates/$templateId/preview'
      path: '/preview'
      fullPath: '/templates/$templateId/preview'
      preLoaderRoute: typeof TemplatesTemplateIdPreviewRouteImport
      parentRoute: typeof TemplatesTemplateIdRoute
    }
    '/templates/$templateId/share': {
      id: '/templates/$templateId/share'
      path: '/share'
      fullPath: '/templates/$templateId/share'
      preLoaderRoute: typeof TemplatesTemplateIdShareRouteImport
      parentRoute: typeof TemplatesTemplateIdRoute
    }
    '/templates/share/$token': {
      id: '/templates/share/$token'
      path: '/share/$token'
      fullPath: '/templates/share/$token'
      preLoaderRoute: typeof TemplatesShareTokenRouteImport
      parentRoute: typeof TemplatesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudioRoute: typeof AdminStudioRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLicensesIndexRoute: typeof AdminLicensesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssetsRoute: AdminAssetsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminContentRoute: AdminContentRoute,
  AdminImportRoute: AdminImportRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudioRoute: AdminStudioRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLicensesIndexRoute: AdminLicensesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface TemplatesTemplateIdRouteChildren {
  TemplatesTemplateIdPreviewRoute: typeof TemplatesTemplateIdPreviewRoute
  TemplatesTemplateIdShareRoute: typeof TemplatesTemplateIdShareRoute
}

const TemplatesTemplateIdRouteChildren: TemplatesTemplateIdRouteChildren = {
  TemplatesTemplateIdPreviewRoute: TemplatesTemplateIdPreviewRoute,
  TemplatesTemplateIdShareRoute: TemplatesTemplateIdShareRoute,
}

const TemplatesTemplateIdRouteWithChildren =
  TemplatesTemplateIdRoute._addFileChildren(TemplatesTemplateIdRouteChildren)

interface TemplatesRouteChildren {
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRouteWithChildren
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesShareTokenRoute: typeof TemplatesShareTokenRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesTemplateIdRoute: TemplatesTemplateIdRouteWithChildren,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesShareTokenRoute: TemplatesShareTokenRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BrandKitRoute: BrandKitRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  CustomDesignRoute: CustomDesignRoute,
  DemoRoute: DemoRoute,
  ImportRoute: ImportRoute,
  LibraryRoute: LibraryRoute,
  LicenseRoute: LicenseRoute,
  LoginRoute: LoginRoute,
  OpenRoute: OpenRoute,
  OwnerVaultRoute: OwnerVaultRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PurchaseRoute: PurchaseRoute,
  StudioRoute: StudioRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  TermsRoute: TermsRoute,
  WorkspaceRoute: WorkspaceRoute,
  Char1575Char1604Char1607Char1608Char1610Char1577Route:
    Char1575Char1604Char1607Char1608Char1610Char1577Route,
  ApiAppVersionRoute: ApiAppVersionRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  SCodeRoute: SCodeRoute,
  ShareTokenRoute: ShareTokenRoute,
  TCodeRoute: TCodeRoute,
  EditorIndexRoute: EditorIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLicenseActivateRoute: ApiLicenseActivateRoute,
  ApiLicenseDeactivateRoute: ApiLicenseDeactivateRoute,
  ApiLicenseValidateRoute: ApiLicenseValidateRoute,
  ApiTemplatesThumbnailRoute: ApiTemplatesThumbnailRoute,
  ApiWebhooksGumroadRoute: ApiWebhooksGumroadRoute,
  ApiWebhooksKeygenRoute: ApiWebhooksKeygenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
